id: IA00A0043
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T08:08:16+00:00'
last_modified: '2022-06-07T18:35:05.682480+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23601
  title: དག་ཡིག་སྟོང་ཐུན་སྤར་བཅང་མ་དང་དེའི་འགྲེལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    60A7:
      image_group_id: I1KG23643
      title: ''
      total_pages: 66
      order: 1
      base_file: 60A7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
